# Generated by Django 4.1 on 2023-01-02 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtrack_app', '0003_debtor_alter_userprofile_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=65, null=True)),
                ('surname', models.CharField(blank=True, max_length=65, null=True)),
                ('address', models.CharField(blank=True, max_length=65, null=True)),
                ('phone', models.CharField(blank=True, max_length=65, null=True)),
                ('email', models.CharField(blank=True, max_length=65, null=True)),
                ('amount_owed', models.CharField(blank=True, max_length=65, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 2, 9, 2, 23, 861058, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 2, 9, 2, 23, 861058, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.DeleteModel(
            name='Debtor',
        ),
    ]
