# Generated by Django 4.1 on 2023-01-02 09:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gtrack_app', '0004_debtors_alter_userprofile_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtors',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 2, 9, 31, 46, 422257, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 2, 9, 31, 46, 422257, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
