# Generated by Django 4.1 on 2023-01-03 08:53

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gtrack_app', '0005_debtors_client_id_alter_userprofile_date_created_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Debtors',
            new_name='Debtor',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 3, 8, 53, 28, 946957, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 3, 8, 53, 28, 946957, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
