# Generated by Django 4.1 on 2023-01-03 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtrack_app', '0006_rename_debtors_debtor_alter_userprofile_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtor',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 3, 9, 19, 57, 666810, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 3, 9, 19, 57, 666810, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
