# Generated by Django 4.1 on 2023-01-03 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtrack_app', '0007_remove_debtor_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 3, 10, 8, 0, 750149, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 3, 10, 8, 0, 750149, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
