# Generated by Django 4.1 on 2023-01-03 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtrack_app', '0008_alter_debtor_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 3, 10, 56, 40, 986211, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 3, 10, 56, 40, 986211, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
