# Generated by Django 4.1.4 on 2023-02-05 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtrack_app', '0014_rename_amount_owed_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='date_captured',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 5, 14, 26, 25, 112476, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 5, 14, 26, 25, 112476, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
