# Generated by Django 4.1 on 2023-02-11 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtrack_app', '0015_debtor_date_captured_alter_userprofile_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='amount_owed',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 10, 15, 53, 765711, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 11, 10, 15, 53, 765711, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
