# Generated by Django 4.1 on 2023-02-11 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtrack_app', '0016_alter_debtor_amount_owed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_payed',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='balance_left',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 10, 23, 45, 541880, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 11, 10, 23, 45, 541880, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
