# Generated by Django 4.1 on 2023-02-21 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtrack_app', '0019_alter_debtor_amount_owed_alter_payment_balance_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 10, 2, 19, 753450, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 21, 10, 2, 19, 753450, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
