# Generated by Django 4.1.4 on 2023-03-19 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtrack_app', '0022_alter_userprofile_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 14, 11, 9, 347485, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 19, 14, 11, 9, 347485, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
