# Generated by Django 4.1.4 on 2023-03-29 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtrack_app', '0023_alter_userprofile_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('email_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('email_message', models.CharField(blank=True, max_length=500, null=True)),
                ('recipient', models.CharField(blank=True, max_length=50, null=True)),
                ('time_sent', models.DateTimeField(default=datetime.datetime(2023, 3, 29, 17, 30, 16, 599878, tzinfo=datetime.timezone.utc))),
                ('attachment', models.FileField(blank=True, null=True, upload_to='uploads/email_attachments')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 17, 30, 16, 597880, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 29, 17, 30, 16, 597880, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
