# Generated by Django 3.2.18 on 2023-10-19 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gtrack_app', '0024_notification_alter_userprofile_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='guarantors_email',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='debtor',
            name='guarantors_name',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='debtor',
            name='guarantors_phone',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 19, 11, 34, 24, 892247, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 19, 11, 34, 24, 891249, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 19, 11, 34, 24, 892247, tzinfo=utc), null=True),
        ),
    ]
