# Generated by Django 3.2.18 on 2023-10-21 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gtrack_app', '0025_auto_20231019_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_seen',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_person',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_person_phone',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state_country',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 21, 12, 8, 29, 231011, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 21, 12, 8, 29, 229013, tzinfo=utc)),
        ),
    ]
