# Generated by Django 3.2.18 on 2023-10-21 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gtrack_app', '0026_auto_20231021_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='notification',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 21, 12, 10, 8, 932222, tzinfo=utc)),
        ),
    ]
