# Generated by Django 3.2.18 on 2023-10-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtrack_app', '0028_auto_20231021_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='client',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='debtor',
            new_name='debtor_id',
        ),
    ]
